# -*- coding: utf-8 -*-
"""Sarcasm_predictor

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VFTiDqnUPmLxwaQn9VDVNWkVtpM9_SbB
"""

import numpy as np
import keras
from keras.preprocessing.text import *
from keras.preprocessing.sequence import pad_sequences
import pandas as pd

model=keras.models.load_model('model1_85%.h5')

df=pd.read_json('Sarcasm_Headlines_Dataset.json',lines=True)

Y=df.is_sarcastic
X=df.headline

token=Tokenizer()#num_words=max_words)
token.fit_on_texts(X)

def prepare(text):
  #token=Tokenizer()#num_words=max_words)
  #token.fit_on_texts(text)
  sequences=token.texts_to_sequences(text)
  seq=pad_sequences(sequences, padding='post', maxlen=40)
  #print(token.word_index)
  return seq

text=input(' enter text  ')
prediction = model.predict([prepare([text])])
print(prediction[0][0])
print('lesser the value, less sarcastic the text is')